name: dualpop_base_app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
   #packages from github
  dualpop_core:
    git:
      url: https://github.com/dualpop-app/dualpop_core
      ref: main
  dualpop_commons_dependencies:
    git:
      url: https://github.com/dualpop-app/dualpop_commons_dependencies
      ref: main
      
  cupertino_icons: ^1.0.2

 
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true
